import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBars,
  faBuildingColumns,
  faCalendarDays,
  faCashRegister,
  faCheck,
  faClock,
  faDownload,
  faEdit,
  faExclamationTriangle,
  faFileExport,
  faFlag,
  faGaugeHigh,
  faPen,
  faPlus,
  faRotateLeft,
  faSave,
  faSpinner,
  faTrash,
  faTrophy,
  faUserEdit,
  faUserPlus,
  faUsers,
  faWallet
} from '@fortawesome/free-solid-svg-icons';

export const adminMenuIcons = {
  dashboard: faGaugeHigh,
  groups: faUsers,
  schedule: faCalendarDays,
  register: faUserPlus,
  members: faUserEdit,
  winners: faTrophy,
  payments: faWallet,
  bank: faBuildingColumns,
  cash: faCashRegister,
  reports: faArrowUpRightFromSquare
} as const;

export const adminUiIcons = {
  mobileMenu: faBars,
  collapseLeft: faArrowLeft,
  collapseRight: faArrowRight,
  edit: faPen,
  delete: faTrash,
  save: faSave,
  reset: faRotateLeft,
  export: faFileExport,
  verify: faCheck,
  flag: faFlag,
  release: faArrowUpRightFromSquare,
  add: faPlus,
  post: faArrowDown,
  match: faCheck,
  open: faArrowRight,
  warning: faExclamationTriangle,
  schedule: faClock,
  refresh: faRotateLeft,
  download: faDownload,
  spin: faSpinner,
  bank: faBuildingColumns,
  cash: faCashRegister,
  winner: faTrophy,
  team: faUsers,
  member: faUserEdit,
  register: faUserPlus
} as const;